general:
  seed: 3
  path_to_data: '../data/'
  path_to_data_raw: '../data/raw/'

dataverse:
  path_to_token: '../../.aa_secrets/dataverse_token'
  base_url: 'https://dataverse.harvard.edu'  
  BuildingElectricity_raw:
    persistentId: #'doi:10.7910/DVN/T3OK7E'
    saving_path: 'datasets/BuildingElectricity/raw/'
  BuildingElectricity:
    persistentId: 'doi:10.7910/DVN/O2MDHX'
    saving_path: 'datasets/BuildingElectricity/processed/'
  WindFarm_raw:
    persistentId: #'doi:10.7910/DVN/BCDE1C'
    saving_path: 'datasets/BuildingElectricity/raw/'
    

BuildingElectricity:
    subtask_list: ['buildings_92', 'buildings_451']
    prediction_window: 96 # in quarter hours (15-min)
    historic_window: 24 # in hours
    meteo_name_list: ['air_density', 'cloud_cover', 'precipitation', 
    'radiation_surface','radiation_toa', 'snow_mass', 'snowfall', 'temperature',
    'wind_speed']
    temporal_test_split: 0.15
    spatial_test_split: 0.2
    val_test_split: 0.2
    data_per_file: 150_000
    
WindFarm:
    subtask_list: ['days_245', 'days_177']
    prediction_window: 288
    historic_window: 288
    fseries_name_list: ['Wspd', 'Wdir', 'Etmp', 'Itmp', 'Ndir', 'Pab1', 'Pab2',
    'Pab3', 'Prtv', 'Patv']
    temporal_test_split: 0.25
    spatial_test_split: 0.2
    val_test_split: 0.2
    subsample_frac: 1
    data_per_file: 50_000
    
UberMovement:
    subtask_list: ['cities_10', 'cities_20', 'cities_43']
    temporal_test_split: 0.22
    spatial_test_split: 0.2
    val_test_split: 0.18
    subsample_frac: 1
    data_per_file: 20_000_000
    
Climart:
    subtask_list: ['pristine', 'clear_sky']
    temporal_test_split: 0.2
    spatial_test_split: 0.35
    val_test_split: 0.2
    subsample_frac: 1
    data_per_file_pristine: 80_000
    data_per_file_clearsky: 35_000
    
OpenCatalyst:
    chunk_size_opencatalyst: 150_000
    subsample_opencatalyst: 0.2
    
    
