general:
    seed: 3
    path_to_data: '../data/'
    path_to_data_raw: '../data/raw/'


building_electricity:
    subtask_list: ['buildings_92', 'buildings_451']
    prediction_window: 96
    historic_window: 96
    meteo_name_list: ['air_density', 'cloud_cover', 'precipitation', 
    'radiation_surface','radiation_toa', 'snow_mass', 'snowfall', 'temperature',
    'wind_speed']
    temporal_test_split: 0.15
    spatial_test_split: 0.2
    val_test_split: 0.2
    datapoints_per_file: 150_000


uber_movement:
    subtask_list: ['cities_10', 'cities_20', 'cities_43']
    temporal_test_split: 0.22
    spatial_test_split: 0.2
    val_test_split: 0.18
    subsample_frac: 1
    datapoints_per_file: 20_000_000


climart:
    subtask_list: ['pristine', 'clear_sky']
    temporal_test_split: 0.2
    spatial_test_split: 0.2
    val_test_split: 0.2
    subsample_frac: 0.2
    datapoints_per_file: 35_000


open_catalst:
    chunk_size_opencatalyst: 150_000
    subsample_opencatalyst: 0.2

