general:
  seed: 3
  path_to_data: '../data/'
  path_to_data_raw: '../data/raw/'
  baseline_results_dir: "baseline_results/"
  analyse_results_dir: "analyse_results/"

dataverse:
  path_to_token: '../../.aa_secrets/dataverse_token'
  base_url: 'https://dataverse.harvard.edu'  
  BuildingElectricity:
    persistentId: #'doi:10.7910/DVN/O2MDHX'
    saving_path: 'datasets/BuildingElectricity/processed/'
  WindFarm:
    persistentId: #'doi:10.7910/DVN/LEGKGU'
    saving_path: 'datasets/WindFarm/processed/'
  UberMovement:
    persistentId: 'doi:10.7910/DVN/ONY86P'
    saving_path: 'datasets/UberMovement/processed/'
  ClimART:
    persistentId: #'doi:10.7910/DVN/0OUKSF'
    saving_path: 'datasets/ClimART/processed/'
  Polianna:
    persistentId: #'doi:10.7910/DVN/ID2YXD'
    saving_path: 'datasets/Polianna/processed/'
  BuildingElectricity_raw:
    persistentId: #'doi:10.7910/DVN/T3OK7E'
    saving_path: 'datasets/BuildingElectricity/raw/'
  WindFarm_raw:
    persistentId: #'doi:10.7910/DVN/BCDE1C'
    saving_path: 'datasets/WindFarm/raw/'
  UberMovement_raw:
    persistentId: 'doi:10.7910/DVN/QRUZOU'
    saving_path: 'datasets/UberMovement/raw/'
  Polianna_raw:
    persistentId: ''
    saving_path: 'datasets/Polianna/raw/'
    
BuildingElectricity:
  subtask_list: ['buildings_92', 'buildings_451']
  prediction_window: 96 # in quarter hours (15-min)
  historic_window: 24 # in hours
  meteo_name_list: ['air_density', 'cloud_cover', 'precipitation', 
    'radiation_surface','radiation_toa', 'snow_mass', 'snowfall', 
    'temperature', 'wind_speed']
  temporal_test_split: 0.15
  spatial_test_split: 0.2
  val_test_split: 0.2
  data_per_file: 150_000
    
WindFarm:
  subtask_list: ['days_245', 'days_177']
  prediction_window: 288 # in 10-min
  historic_window: 288 # in 10-min
  fseries_name_list: ['Wspd', 'Wdir', 'Etmp', 'Itmp', 'Ndir', 'Pab1', 'Pab2',
    'Pab3', 'Prtv', 'Patv']
  temporal_test_split: 0.25
  spatial_test_split: 0.2
  val_test_split: 0.2
  subsample_frac: 1
  data_per_file: 33_000
    
UberMovement:
  subtask_list: ['cities_10', 'cities_20', 'cities_43']
  temporal_test_split: 0.22
  spatial_test_split: 0.2
  val_test_split: 0.18
  subsample_frac: 1
  data_per_file: 6_500_000
    
ClimART:
  subtask_list: ['pristine', 'clear_sky']
  temporal_test_split: 0.2
  spatial_test_split: 0.35
  val_test_split: 0.2
  subsample_frac: 1
  data_per_file_pristine: 80_000
  data_per_file_clearsky: 36_000
    
    
OpenCatalyst:
  subtask_list : ['oc20_s2ef'] #['oc20_s2ef', 'oc20_is2res', 'oc22_s2ef', oc22_is2res]
  num_features: ['AtomicMass', 'Electronegativity', 'AtomicRadius', 
    'IonizationEnergy', 'ElectronAffinity', 'MeltingPoint', 'BoilingPoint',
    'Density']
  ord_features: ['StandardState', 'GroupBlock']
  onehot_features: ['OxidationStates']
  spatial_test_split: 0.3
  val_test_split: 0.2
  subsample_frac: 1
  data_per_file: 100_000
  
  
Polianna:
  subtask_list : ['article_level', 'text_level']
  data_col_list : ['Date created', 'Treaty', 'Text', 'Tokens', 'Curation', 
    'Form']
  rename_col_dict : {
    'Text' : 'article_text',
    'Tokens' : 'article_token',
    'Curation' : 'annotation',
    'Date created' : 'date',
    'Form' : 'form',
    'Treaty' : 'treaty'
  }
  temporal_test_split: 0.5
  spatial_test_split: 0.5
  val_test_split: 0.2
  data_per_file: 500
  
    
    
    
