version: '3.9'
services:
    integrationtest:
        build:
            context: ./
            dockerfile: Docker_testintegration/Dockerfile
        volumes: 
            - .:/EnergyTransitionTasks
            - ../shared_cp:/shared_cp

    unittest:
        build:
            context: ./
            dockerfile: Docker_testunit/Dockerfile
        volumes:
            - .:/EnergyTransitionTasks
            - ../shared_cp:/shared_cp

